# Day 13 Task -
Create arrays with all the data types available in numpy
Integer

In [9]:

import numpy as np
b = np.array([1, 2, 3, 4], dtype = 'int')
print(b)
print(b.dtype)

[1 2 3 4]
int32


In [11]:

b= np.array([True, False, False, True], dtype = 'bool')
print(b)
print(b.dtype)

[ True False False  True]
bool


In [13]:

b = np.array([1.6, 2.9, 3.3, 4.6], dtype = 'float')
print(b)
print(b.dtype)

[1.6 2.9 3.3 4.6]
float64


In [14]:

b = np.array([1+3j, 2+4j, 6+8.7j, 8+3.4j], dtype = 'complex_')
print(b)
print(b.dtype)

[1.+3.j  2.+4.j  6.+8.7j 8.+3.4j]
complex128


In [15]:
b = np.array(['a', 'b', 'c', 'd'], dtype = 'S')
print(b)
print(b.dtype)

[b'a' b'b' b'c' b'd']
|S1


In [16]:
b = np.array([[1, 2], [3, 4], [4.6, 7.4], ['chandler', 'jake']], dtype = 'O')
print(b)
print(b.dtype)

[[1 2]
 [3 4]
 [4.6 7.4]
 ['chandler' 'jake']]
object


In [17]:

b = np.array([1, 2, 3, 4], dtype = 'U')
print(b)
print(b.dtype)

['1' '2' '3' '4']
<U1


In [18]:

b= np.array([1, 2, 3, 4], dtype = 'uint8')
print(b)
print(b.dtype)

[1 2 3 4]
uint8
